# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V5xYKSRCKZ1p965Nycv6U90-UbbRc_aN
"""

pip install ping3

from ping3 import ping
import csv

domens = ['youtube.com',"web.telegram.org","profi.ru","vk.com","sky.pro","drive.google.com","mail.google.com","yandex.ru","kwork.ru","baserow.io"]
RTT={}
RTT_par={}
RTT_max_par={}
RTT_min_par={}
lost={}
for i in domens:
    rtt_list =[]
    for j in range(4):
      a = ping(i)
      if a != None:
        rtt_list.append(a)
    RTT[i] = rtt_list
for i in domens:
  if RTT[i]:
    RTT_par[i] = sum(RTT[i]) / len(RTT[i])
  else:
    RTT_par[i] = None
for i in domens:
  lost[i]= 100*((4- len(RTT[i]))/4)
for i in domens:
  if RTT[i]:
    RTT_max_par[i] = max(RTT[i])
  else:
    RTT_max_par[i] = None
for i in domens:
  if RTT[i]:
    RTT_min_par[i] = min(RTT[i])
  else:
    RTT_min_par[i] = None
results=[]
for i in domens:
  results.append({
      'domain': i,
      'avg_rtt_sec': RTT_par[i],
      'max_rtt_sec': RTT_max_par[i],
      'loss_pct': lost[i],
      'min_rtt_sec': RTT_min_par[i]
  })
filednames=['domain','avg_rtt_sec','max_rtt_sec','loss_pct','min_rtt_sec']
with open("spisok.csv","w") as spis:
  writer = csv.DictWriter(spis,fieldnames=filednames)
  writer.writeheader()
  writer.writerows(results)

